---
- name: Deploy and Execute ETCD Backup Script
  hosts: etcd_nodes
  become: yes
  tasks:
    - name: Copy ETCD Backup Script to Nodes
      copy:
        src: ./etcd_backup_script.sh
        dest: /opt/etcd_backup_script.sh
        mode: '0755'
    - name: Copy ETCD Restore Script to Nodes
      copy:
        src: ./restore_etcd_backup.sh
        dest: /opt/restore_etcd_backup.sh
        mode: '0755'
    - name: Execute ETCD Backup Script
      shell:
        cmd: /opt/etcd_backup_script.sh
